Slots from u32 to BigNum
Emurgo/cardano-serialization-lib pull request #430
Opened 2022-05-04 13:08 UTC by lisicky

2022-05-14 09:42 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
> +   * Returns a new HeaderBody.
Add comment here to "use `.new_headerbody` instead"

2022-05-14 09:43 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
> +   * Otherwise will just return JsError.
```suggestion
   * Otherwise will just raise an error.
```

2022-05-14 09:43 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
> +   * Otherwise will just return JsError.
Add comment here to "use `.slot_bignum` instead"

2022-05-14 09:45 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
> +   * Returns a new HeaderBody.
Mention in the comment that it "uses simplified slot type as number"

2022-05-14 09:46 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
>    static new(slot: number, tx_index: number, cert_index: number): Pointer;
Mark `.new` as deprecated, mention that it "uses simplified slot number type", and mention to "use `.new_pointer` instead

2022-05-14 09:50 UTC, vsubhuman commented on rust/pkg/cardano_serialization_lib.js.flow
> +   * Returns a new TransactionBody.
Add comment to "use `.new_tx_body` instead"

2022-05-14 09:59 UTC, vsubhuman reviewed
/check

2022-05-14 19:54 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Otherwise will just return JsError.
```suggestion
    /// Otherwise will just raise an error.
    /// Use `.ttl_bignum` instead
```

2022-05-14 19:56 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Set validity_start_interval value.
```suggestion
    /// Uses outdated slot number format.
    /// Use `.set_validity_start_interval_bignum` instead.
```

2022-05-14 19:57 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Otherwise will just return JsError.
```suggestion
    /// Otherwise will just raise an error.
    /// Use `.validity_start_interval_bignum` instead.
```

2022-05-14 19:58 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Returns a new TransactionBody.
```suggestion
    /// This constructor uses outdated slot number format.
    /// Use `.new_tx_body` instead
```

2022-05-14 20:00 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Otherwise will just return JsError.
```suggestion
    /// Otherwise will just raise an error.
    /// Use `.slot_bignum` instead 
```

2022-05-14 20:01 UTC, vsubhuman commented on rust/src/lib.rs
> +    /// Returns a new TimelockStart from Slot32 (u32) value.
```suggestion
    /// This constructor uses outdated slot number format.
    /// Use `.new_timelockstart` instead.
```

2022-05-14 20:05 UTC, vsubhuman commented on rust/src/utils.rs
> +}
nice

2022-05-14 20:06 UTC, vsubhuman requested changes
See comments. Fix all similar deprecation messages

2022-05-16 09:44 UTC, lisicky commented
> See comments. Fix all similar deprecation messages

I have fixed it. Can you check ?

2022-05-16 10:14 UTC, vsubhuman commented
@rooooooooob , check please, building on top of your change to provide backward compatibility and fix all usages of slot

2022-05-16 11:07 UTC, vsubhuman approved these changes

2022-05-16 13:34 UTC, vsubhuman reviewed
/check

2022-05-17 13:14 UTC, merged

2022-05-17 18:04 UTC, rooooooooob reviewed
LGTM functionality-wise although we're definitely getting a more complex API with all the variants

2022-05-17 19:52 UTC, vsubhuman commented
> LGTM functionality-wise although we're definitely getting a more complex API with all the variants

Will remove the deprecated methods in one of the next major versions. The main idea right now is that the BigNum slot support is only **really** needed for deserialisation to be able to handle rare edge cases created by someone else. For majority of users that only use the library to build txs the new bignum part of the API will not be necessary.